version: '3'

volumes:
  db:
    driver: local

services:
  server:
    image: cathd/fwo:latest
    environment:
      BOT_TOKEN: "184570216:AAF5G80kEX_0tdwXPcnXO8Uttqc21EUPqaA"
    restart: always
  db:
    image: mongo:4.4
    mem_limit: 512M
    cpu_percent: 60
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fworootpassword
    volumes:
    - db:/data/db
