version: '3'

volumes:
  db:
    driver: local
services:
  server:
    build: .
    env_file:
      - .tg-token
    restart: always
    links:
      - "db"
    depends_on:
      - db
  db:
    image: mongo:4.4
    mem_limit: 512M
    cpu_percent: 60
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fworootpassword
    volumes:
    - db:/data/db
  test_db:
    image: mongo:6.0
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: fworootpassword
    networks:
    - mongo-network
    volumes:
    - db:/data/test_db
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u root -p fworootpassword --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: ["--replSet", "dbrs", "--bind_ip_all"]
networks:
  mongo-network:
    driver: bridge