name: FWO Test

on:
  push:
    branches:
      - dev-*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test
      env:
        CI: true
    - name: Deploy MasterBot
      uses: contention/action-rsync-deploy@master
      env:
        secrets: ${{ DEPLOY_KEY }}
        args: '-avzr --delete --exclude /uploads/ codeship@159.89.227.216:~/fwo-test/'
