name: FWO Test

on:
  push:
    branches: 
      - dev-*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test
      env:
        CI: true
    - name: deploy test bot
      uses: contention/action-rsync-deploy@master
      env:
        args: '-avzr --delete --exclude .htaccess --exclude /uploads/ user@server.com:/srv/myapp/public/htdocs/'  
